import '~/styles/globals.css'

import { type Metadata, } from 'next'
import { oxygen } from '~/fonts'

import { TRPCReactProvider, } from '~/trpc/react'
import NavBar from '~/components/NavBar'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico', }],
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' className={`${oxygen.className}`}>
      <body>
        <NavBar />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
