import '~/styles/globals.css'

import { type Metadata, } from 'next'
import { oxygen } from '~/fonts'

import { TRPCReactProvider, } from '~/trpc/react'
import NavBar from '~/components/NavBar'
import Footer from '~/components/Footer'
import { cn } from '~/lib/utils'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico', }],
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' className={cn(`${oxygen.className}`, 'scroll-smooth')}>
      <body className='flex flex-col min-h-screen'>
        <NavBar />
        <TRPCReactProvider>{
          <div className='flex-1'>
            {children}
          </div>
        }</TRPCReactProvider>
        <Footer />
      </body>
    </html>
  )
}
